"use client";

import Link from "next/link";
import { useState } from "react";
import { ArrowLeft, Bot, CheckCircle2, Network, X } from "lucide-react";

import { ProviderCard } from "@/components/company/provider-card";
import { OpportunityCard } from "@/components/opportunity/opportunity-card";
import { BuyerIntent, MatchScore, NextBestAction, StatCard, VerificationSummary } from "@/components/shared/signals";
import { Button } from "@/components/ui/button";
import { Badge, Card, EmptyState, ErrorState, Input, PageHeader, Select, Skeleton } from "@/components/ui/primitives";
import { opportunities, providers } from "@/data/mock";

export function DesignSystemGallery() { const [dialog,setDialog]=useState(false); const [drawer,setDrawer]=useState(false); return <div className="min-h-screen bg-background"><header className="sticky top-0 z-30 border-b bg-surface"><div className="mx-auto flex h-16 max-w-7xl items-center justify-between px-4 sm:px-6"><div className="flex items-center gap-3"><span className="flex size-9 items-center justify-center rounded-md bg-brand-600 text-white"><Network className="size-5"/></span><div><p className="text-sm font-semibold">TemuClient Design System</p><p className="text-[10px] text-text-muted">Prototype visual audit</p></div></div><Link className="flex items-center gap-2 text-sm font-semibold text-brand-700" href="/"><ArrowLeft className="size-4"/>Kembali</Link></div></header><main className="mx-auto max-w-7xl space-y-12 px-4 py-10 sm:px-6"><PageHeader eyebrow="Visual source of truth" title="Design System" description="Reusable tokens and interaction patterns for Data, Signal, and Action hierarchy."/>
    <section><h2 className="text-lg font-semibold">Color Tokens</h2><div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-4 lg:grid-cols-8">{[["Canvas","bg-background"],["Surface","bg-surface"],["Brand","bg-brand-600 text-white"],["Brand Subtle","bg-brand-50"],["Success","bg-success-600 text-white"],["Warning","bg-warning-600 text-white"],["Danger","bg-danger-600 text-white"],["Info","bg-info-600 text-white"]].map(([name,color])=><div key={name}><div className={`h-16 rounded-md border ${color}`}/><p className="mt-2 text-xs font-medium">{name}</p></div>)}</div></section>
    <section><h2 className="text-lg font-semibold">Typography</h2><Card className="mt-4 space-y-4 p-5"><p className="text-4xl font-semibold tracking-tight">Hero / 40</p><p className="text-2xl font-semibold">Page title / 24</p><p className="text-lg font-semibold">Section title / 18</p><p className="text-base">Body / 16 — Premium B2B intelligence with professional density.</p><p className="text-sm text-text-secondary">Dense UI / 14 — Context and operational copy.</p><p className="text-xs text-text-muted">METADATA / 12</p></Card></section>
    <section className="grid gap-6 lg:grid-cols-2"><div><h2 className="text-lg font-semibold">Buttons & Badges</h2><Card className="mt-4 flex flex-wrap gap-3 p-5"><Button>Primary action</Button><Button variant="outline">Secondary</Button><Button disabled>Disabled</Button>{["neutral","brand","success","warning","danger","info"].map((tone)=><Badge key={tone} tone={tone as "neutral"|"brand"|"success"|"warning"|"danger"|"info"}>{tone}</Badge>)}</Card></div><div><h2 className="text-lg font-semibold">Inputs & Selects</h2><Card className="mt-4 grid gap-3 p-5"><Input placeholder="Search opportunity…"/><Select><option>Choose service</option><option>Software Development</option></Select><Input aria-invalid className="border-danger-600" defaultValue="Invalid value"/><p className="text-xs text-danger-700">Field membutuhkan perbaikan.</p></Card></div></section>
    <section><h2 className="text-lg font-semibold">Signals & Stats</h2><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Card className="p-5"><MatchScore score={94}/></Card><Card className="p-5"><BuyerIntent score={92}/></Card><Card className="p-5"><VerificationSummary expanded score={4}/></Card><StatCard label="Pipeline Value" value="Rp2,35 M" delta="+12%" detail="Weighted Rp1,16 M"/></div></section>
    <section><h2 className="text-lg font-semibold">Opportunity Card</h2><div className="mt-4 grid gap-4 lg:grid-cols-2"><OpportunityCard opportunity={opportunities[0]}/><OpportunityCard compact opportunity={opportunities[1]}/></div></section>
    <section><h2 className="text-lg font-semibold">Provider Card & Next Best Action</h2><div className="mt-4 grid gap-4 lg:grid-cols-2"><ProviderCard provider={providers[0]}/><Card className="p-5"><NextBestAction title="Follow up proposal" description="Proposal belum mendapat respons selama 4 hari." meta="PT Sumber Retail • Rp480 jt"/><NextBestAction title="Schedule discovery" description="Buyer mengusulkan waktu meeting besok." meta="PT Nusantara Logistik"/></Card></div></section>
    <section><h2 className="text-lg font-semibold">Tables</h2><div className="mt-4 overflow-x-auto rounded-lg border bg-surface"><table className="min-w-[650px] w-full text-left text-sm"><thead className="bg-surface-subtle text-xs text-text-secondary"><tr>{["Entity","Signal","Status","Next Action"].map((item)=><th className="p-3 font-medium" key={item}>{item}</th>)}</tr></thead><tbody><tr className="border-t"><td className="p-3 font-semibold">PT Nusantara Logistik</td><td className="p-3">Buyer Intent 92</td><td className="p-3"><Badge tone="success">Verified</Badge></td><td className="p-3 text-brand-700">Review match →</td></tr></tbody></table></div></section>
    <section><h2 className="text-lg font-semibold">Dialogs & Drawers</h2><Card className="mt-4 flex gap-3 p-5"><Button onClick={()=>setDialog(true)}>Open dialog</Button><Button onClick={()=>setDrawer(true)} variant="outline">Open drawer</Button></Card></section>
    <section><h2 className="text-lg font-semibold">Feedback States</h2><div className="mt-4 grid gap-4 lg:grid-cols-2"><EmptyState title="Belum ada opportunity" description="Lengkapi capability agar matching menjadi lebih akurat." action={<Button>Lengkapi Profile</Button>}/><ErrorState/></div></section>
    <section><h2 className="text-lg font-semibold">Skeletons</h2><Card className="mt-4 space-y-4 p-5"><div className="flex gap-3"><Skeleton className="size-10"/><div className="flex-1 space-y-2"><Skeleton className="h-4 w-1/3"/><Skeleton className="h-3 w-2/3"/></div></div><Skeleton className="h-24 w-full"/><div className="grid grid-cols-3 gap-3"><Skeleton className="h-10"/><Skeleton className="h-10"/><Skeleton className="h-10"/></div></Card></section>
    <section><h2 className="text-lg font-semibold">AI Insight</h2><Card className="mt-4 max-w-xl border-brand-100 bg-brand-50 p-5"><div className="flex items-center gap-2 text-brand-700"><Bot className="size-4"/><p className="font-semibold">AI Insight • Draft</p></div><p className="mt-3 text-sm leading-7 text-text-secondary">Budget dan stakeholder signals positif. Libatkan procurement sebelum proposal komersial.</p><p className="mt-3 text-xs text-text-muted">Human review required. Never sent automatically.</p></Card></section>
  </main>{dialog&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-text-primary/30 p-4" onClick={()=>setDialog(false)}><Card aria-modal="true" className="w-full max-w-md p-5 shadow-xl" onClick={(event)=>event.stopPropagation()} role="dialog"><div className="flex justify-between"><h2 className="font-semibold">Confirm prototype action</h2><button onClick={()=>setDialog(false)}><X className="size-4"/></button></div><p className="mt-3 text-sm text-text-secondary">This demonstrates an accessible modal pattern with a clear action hierarchy.</p><div className="mt-6 flex justify-end gap-2"><Button onClick={()=>setDialog(false)} variant="outline">Cancel</Button><Button onClick={()=>setDialog(false)}><CheckCircle2 className="size-4"/>Confirm</Button></div></Card></div>}{drawer&&<div className="fixed inset-0 z-50 bg-text-primary/30" onClick={()=>setDrawer(false)}><aside className="absolute inset-y-0 right-0 w-full max-w-md bg-surface p-5 shadow-xl" onClick={(event)=>event.stopPropagation()}><div className="flex justify-between"><h2 className="font-semibold">Drawer pattern</h2><button onClick={()=>setDrawer(false)}><X className="size-4"/></button></div><p className="mt-4 text-sm leading-6 text-text-secondary">Secondary detail and multi-field actions use a drawer on desktop and a full-height sheet on mobile.</p></aside></div>}</div>; }
