"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { AlertTriangle, Building2, CheckCircle2, Search, ShieldCheck } from "lucide-react";

import { AppShell } from "@/components/shared/app-shell";
import { StatCard, VerificationSummary } from "@/components/shared/signals";
import { Badge, Card, Input, PageHeader, Select } from "@/components/ui/primitives";
import { moderationRows, opportunities } from "@/data/mock";

function AdminTable({ kind }: { kind: "companies" | "opportunities" | "verifications" | "audit" }) {
  const [search, setSearch] = useState("");
  const rows = useMemo(() => moderationRows.filter((row) => row.company.toLowerCase().includes(search.toLowerCase())), [search]);
  const headings = kind === "audit" ? ["Timestamp", "Actor", "Action", "Entity", "Result"] : ["Entity", "Type", "Status", "Risk", "Submitted"];
  return <div className="space-y-5"><PageHeader eyebrow="Platform operations" title={kind === "companies" ? "Companies" : kind === "opportunities" ? "Opportunities" : kind === "verifications" ? "Verification Queue" : "Audit Log"} description="Dense operational view with explicit trust and moderation context." /><Card className="p-3"><div className="grid gap-3 md:grid-cols-[1fr_auto_auto]"><label className="relative"><Search className="absolute left-3 top-3.5 size-4 text-text-muted" /><Input className="pl-9" onChange={(event) => setSearch(event.target.value)} placeholder="Search entity…" /></label><Select aria-label="Status"><option>All status</option><option>Pending</option><option>Verified</option></Select><Select aria-label="Risk"><option>All risk</option><option>Low</option><option>Medium</option></Select></div></Card><div className="overflow-x-auto rounded-lg border bg-surface"><table className="min-w-[760px] w-full text-left text-sm"><thead className="bg-surface-subtle text-xs text-text-secondary"><tr>{headings.map((heading) => <th className="px-4 py-3 font-medium" key={heading}>{heading}</th>)}</tr></thead><tbody>{rows.map((row, index) => kind === "audit" ? <tr className="border-t" key={row.company}><td className="px-4 py-3 text-xs text-text-muted">10 Aug, {10 + index}:24</td><td className="px-4 py-3">Admin Operations</td><td className="px-4 py-3 font-medium">{index % 2 ? "VERIFICATION_REVIEWED" : "ORGANIZATION_UPDATED"}</td><td className="px-4 py-3">{row.company}</td><td className="px-4 py-3"><Badge tone="success">Success</Badge></td></tr> : <tr className="border-t" key={row.company}><td className="px-4 py-3"><Link className="font-semibold hover:text-brand-700" href={kind === "opportunities" ? "/admin/opportunities/warehouse-management" : `/admin/companies/${index + 1}`}>{kind === "opportunities" ? opportunities[index].title : row.company}</Link><p className="mt-1 text-xs text-text-muted">{row.company}</p></td><td className="px-4 py-3">{kind === "verifications" ? index % 2 ? "DOMAIN" : "COMPANY" : row.type}</td><td className="px-4 py-3"><Badge tone={row.status === "Verified" ? "success" : "warning"}>{row.status}</Badge></td><td className="px-4 py-3"><Badge tone={row.risk === "Medium" ? "warning" : "neutral"}>{row.risk}</Badge></td><td className="px-4 py-3 text-text-muted">{row.submitted}</td></tr>)}</tbody></table></div></div>;
}

function AdminDashboard() {
  return <div className="space-y-7"><PageHeader eyebrow="Operations overview" title="Admin Dashboard" description="Trust, verification, and moderation signals across the TemuClient network." /><section className="grid grid-cols-2 gap-3 xl:grid-cols-5"><StatCard label="Pending Verification" value="18" delta="6 new" /><StatCard label="Active Opportunities" value="142" /><StatCard label="Flagged" value="4" /><StatCard label="Providers" value="286" /><StatCard label="Buyers" value="194" /></section><div className="grid gap-5 xl:grid-cols-[1.4fr_0.8fr]"><Card className="overflow-hidden"><div className="border-b p-4"><h2 className="font-semibold">Recent Moderation Activity</h2></div><div className="divide-y">{moderationRows.map((row, index) => <div className="flex items-center gap-4 p-4" key={row.company}><span className="flex size-9 items-center justify-center rounded-md bg-surface-subtle">{index % 2 ? <ShieldCheck className="size-4 text-success-600" /> : <Building2 className="size-4 text-brand-600" />}</span><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{row.company}</p><p className="mt-1 text-xs text-text-muted">{row.type} verification submitted • {row.submitted}</p></div><Badge tone={row.status === "Verified" ? "success" : "warning"}>{row.status}</Badge></div>)}</div></Card><div className="space-y-4"><Card className="border-warning-100 bg-warning-50 p-5"><div className="flex items-center gap-2 text-warning-700"><AlertTriangle className="size-4" /><h2 className="font-semibold">Requires attention</h2></div><p className="mt-3 text-sm leading-6 text-text-secondary">4 opportunities have risk signals and 3 company verifications exceed the review SLA.</p><Link className="mt-4 block text-sm font-semibold text-warning-700" href="/admin/verifications">Open verification queue →</Link></Card><Card className="p-5"><h2 className="font-semibold">Verification coverage</h2><div className="mt-5 space-y-3"><p className="flex justify-between text-sm"><span>Company</span><strong>91%</strong></p><p className="flex justify-between text-sm"><span>Domain</span><strong>84%</strong></p><p className="flex justify-between text-sm"><span>Requirement</span><strong>78%</strong></p></div></Card></div></div></div>;
}

function CompanyReview() { const [action, setAction] = useState<string>(); return <div className="space-y-6"><PageHeader eyebrow="Company review" title="PT Nusantara Logistik" description="Buyer • Surabaya • Created 2 Aug 2026" action={<div className="flex gap-2"><button className="min-h-11 rounded-md border border-danger-100 px-4 text-sm font-semibold text-danger-700" onClick={() => setAction("Suspension review opened")}>Suspend</button><button className="min-h-11 rounded-md bg-brand-600 px-4 text-sm font-semibold text-white" onClick={() => setAction("Company verified")}>Verify</button></div>} />{action && <Card className="border-success-100 bg-success-50 p-4 text-sm text-success-700"><CheckCircle2 className="mr-2 inline size-4" />{action} — prototype only; no admin mutation executed.</Card>}<div className="grid gap-5 lg:grid-cols-[1fr_300px]"><div className="space-y-4">{["Company","Members","Services & Requirements","Activity","Risk Flags"].map((title) => <Card className="p-5" key={title}><h2 className="font-semibold">{title}</h2><p className="mt-3 text-sm leading-7 text-text-secondary">Operational review data for company identity, business context, authorized members, and recent platform activity.</p></Card>)}</div><aside className="space-y-4"><Card className="p-5"><VerificationSummary expanded score={4} /></Card><Card className="p-5"><p className="text-sm font-semibold">Risk assessment</p><Badge className="mt-3" tone="success">Low risk</Badge><p className="mt-3 text-sm text-text-secondary">No duplicate domain, contact, or organization signals detected.</p></Card></aside></div></div>; }

function OpportunityReview() { const [result, setResult] = useState<string>(); return <div className="space-y-6"><PageHeader eyebrow="Opportunity moderation" title="Warehouse Management System" description="PT Nusantara Logistik • Submitted 10 Aug 2026" /><div className="grid gap-5 lg:grid-cols-[1fr_320px]"><div className="space-y-4">{[["Buyer","PT Nusantara Logistik • Domain and company verified."],["Requirement","Multi-warehouse inventory platform with ERP integration."],["Budget & Timeline","Rp250–400 juta • 4–6 bulan • Budget confirmed."],["Contact","Authorized buyer contact available to admin review only."],["History","Draft created → structured → reviewed → submitted."]].map(([title, copy]) => <Card className="p-5" key={title}><h2 className="font-semibold">{title}</h2><p className="mt-3 text-sm leading-7 text-text-secondary">{copy}</p></Card>)}</div><aside className="space-y-4"><Card className="p-5"><VerificationSummary expanded score={4} /></Card><Card className="p-5"><p className="text-sm font-semibold">Risk flags</p><p className="mt-3 text-sm text-success-700">✓ No suspicious duplication</p><p className="mt-2 text-sm text-success-700">✓ Budget evidence provided</p></Card><div className="grid grid-cols-2 gap-2"><button className="min-h-11 rounded-md border text-sm font-semibold" onClick={() => setResult("Information requested")}>Request Info</button><button className="min-h-11 rounded-md border border-danger-100 text-sm font-semibold text-danger-700" onClick={() => setResult("Opportunity rejected")}>Reject</button><button className="min-h-11 rounded-md border text-sm font-semibold" onClick={() => setResult("Opportunity flagged")}>Flag</button><button className="min-h-11 rounded-md bg-brand-600 text-sm font-semibold text-white" onClick={() => setResult("Opportunity verified")}>Verify</button></div>{result && <p className="rounded-md bg-brand-50 p-3 text-xs text-brand-700">{result} — prototype only.</p>}</aside></div></div>; }

export function AdminPrototype({ slug }: { slug: string[] }) {
  const view = slug.join("/"); let content: React.ReactNode;
  if (!view) content = <AdminDashboard />;
  else if (view === "companies") content = <AdminTable kind="companies" />;
  else if (view.startsWith("companies/")) content = <CompanyReview />;
  else if (view === "opportunities") content = <AdminTable kind="opportunities" />;
  else if (view.startsWith("opportunities/")) content = <OpportunityReview />;
  else if (view === "verifications") content = <AdminTable kind="verifications" />;
  else content = <AdminTable kind="audit" />;
  return <AppShell persona="admin">{content}</AppShell>;
}
